"use strict"

module.exports = {
  RESET: 'RESET',
  RECEIVE_RAW_MODEL: 'RECEIVE_RAW_MODEL',
  RENTAL_AUTOCOMPLETE_CITY: 'RENTAL_AUTOCOMPLETE_CITY',
  CLEAR_RENTAL_AUTOCOMPLETE_CITY: 'CLEAR_RENTAL_AUTOCOMPLETE_CITY',
  RENTAL_SEARCH_CITY: 'RENTAL_SEARCH_CITY',
  CLEAR_RENTAL_SEARCH_CITY: 'CLEAR_RENTAL_SEARCH_CITY'
}
